image: "node:16-alpine"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install --frozen-lockfile --check-files --non-interactive
    - npm run build --base=$CI_PAGES_URL
    - cp -a dist/. public/
  artifacts:
    paths:
      - public

deploy-staging:
  stage: deploy
  script:
    - echo 'Staging deployment job'
  artifacts:
    paths:
      - public
  except:
    - master