image: node:lts
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    # Debug: Print the variable (masked) to verify it exists
    - echo "Checking if VITE_APP_API_URL exists: ${VITE_APP_API_URL:+true}"
    # Create .env file
    - echo "VITE_APP_API_URL=$VITE_APP_API_URL" > .env
    # Debug: Check .env file was created (without showing content)
    - ls -la .env
    # Build with verbose logging if possible
    - npm run build
    # Debug: Check what's in the dist directory
    - ls -la dist/
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH